daigbt – odepack
daigbt Subroutine
30 statements
Source File
public subroutine daigbt(res, adda, Neq, T, Y, Ydot, Mb, Nb, Pw, Ipvt, Ier)
This subroutine computes the initial value of the vector YDOT satisfying
 A * YDOT = g(t,y)
when A is nonsingular. It is called by DLSOIBT for initialization only, when ISTATE = 0 . DAIGBT returns an error flag IER:
IER  =  0  means DAIGBT was successful.
IER .ge. 2 means RES returned an error flag IRES = IER.
IER .lt. 0 means the A matrix was found to have a singular
           diagonal block (hence YDOT could not be solved for).
Arguments
Type Intent Optional Attributes Name
real :: res
real :: adda
integer :: Neq(*)
real(kind=dp) :: T
real(kind=dp) :: Y(*)
real(kind=dp) :: Ydot(*)
integer, intent(inout) :: Mb
integer, intent(inout) :: Nb
real(kind=dp) :: Pw(*)
integer :: Ipvt(*)
integer, intent(inout) :: Ier
Calls
Called by
Call graph
daigbt calls dgefa, dgesl
dgefa calls daxpy, dscal
dgesl calls daxpy
dlsoibt calls daigbt