dainvg – odepack
dainvg Subroutine
49 statements
Source File
public subroutine dainvg(res, adda, Neq, T, Y, Ydot, Miter, Ml, Mu, Pw, Ipvt, Ier)
This subroutine computes the initial value of the vector YDOT satisfying
 A * YDOT = g(t,y)
when A is nonsingular. It is called by DLSODI for initialization only, when ISTATE = 0 . DAINVG returns an error flag IER:
IER  =  0  means DAINVG was successful.
IER .ge. 2 means RES returned an error flag IRES = IER.
IER .lt. 0 means the a-matrix was found to be singular.
Arguments
Type Intent Optional Attributes Name
real :: res
real :: adda
integer, intent(inout) :: Neq
real(kind=dp) :: T
real(kind=dp) :: Y(*)
real(kind=dp) :: Ydot(*)
integer, intent(inout) :: Miter
integer, intent(inout) :: Ml
integer, intent(inout) :: Mu
real(kind=dp) :: Pw(*)
integer :: Ipvt(*)
integer, intent(inout) :: Ier
Calls
Called by
Call graph
dainvg calls daxpy, dgefa, dgesl, dscal
dgefa calls daxpy, dscal
dgesl calls daxpy
dlsodi calls dainvg