daxpy – odepack
daxpy Subroutine
45 statements
Source File
public subroutine daxpy(N, Da, Dx, Incx, Dy, Incy)
NAME
daxpy(3f) - [M_odepack::matrix] Compute a constant times a vector plus a vector.
SYNOPSIS
subroutine daxpy(N,Da,Dx,Incx,Dy,Incy)
integer,intent(in)          :: N
real(kind=dp),intent(in)    :: Da
real(kind=dp),intent(in)    :: Dx(*)
integer,intent(in)          :: Incx
real(kind=dp),intent(inout) :: Dy(*)
integer,intent(in)          :: Incy
DESCRIPTION
daxpy(3f) computes a constant times a vector plus a vector. It uses unrolled loops for increments equal to one.
Overwrite double precision DY with double precision DADX + DY. For I = 0 to N-1, replace DY(LY+IINCY) with DADX(LX+IINCX) + DY(LY+I*INCY),
where LX = 1 if INCX .GE. 0, else LX = 1+(1-N)*INCX, and LY is defined in a similar way using INCY.
INPUT OPTIONS
N
number of elements in input vector(s)
DA
double precision scalar multiplier
DX
double precision vector with N elements
INCX
storage spacing between elements of DX
DY
double precision vector with N elements
INCY
storage spacing between elements of DY
RETURNS
DY
double precision result (unchanged if N .LE. 0)
REFERENCES
B L A S Subprogram
C. L. Lawson, R. J. Hanson, D. R. Kincaid and F. T. Krogh, Basic linear algebra subprograms for Fortran usage, Algorithm No. 539, Transactions on Mathematical Software 5, 3 (September 1979), pp. 308-323.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
real(kind=dp), intent(in) :: Da
real(kind=dp), intent(in) :: Dx(*)
integer, intent(in) :: Incx
real(kind=dp), intent(inout) :: Dy(*)
integer, intent(in) :: Incy
Called by
Call graph
dainvg calls daxpy, dgefa, dgesl
dgefa calls daxpy
dgesl calls daxpy
dprepj calls daxpy, dgefa
dprepji calls daxpy, dgefa
dprja calls daxpy, dgefa
dsolsy calls daxpy, dgesl
dstodpk calls daxpy
dstoka calls daxpy
daigbt calls dgefa, dgesl
dlsodi calls dainvg
dlsodkr calls dstoka
dlsodpk calls dstodpk
dpjibt calls dgefa, dgesl
dslsbt calls dgesl
dlsoibt calls daigbt