dscal – odepack
dscal Subroutine
33 statements
Source File
public subroutine dscal(N, Da, Dx, Incx)
NAME
dscal(3f) - [M_odepack::matrix] Multiply a vector by a constant.
SYNOPSIS
subroutine dscal(N,Da,Dx,Incx)
integer , intent(in) :: N
real(kind=dp) , intent(in) :: Da
real(kind=dp) , intent(inout) , dimension(*) :: Dx
integer , intent(in) :: Incx
DESCRIPTION
Replace double precision DX by double precision DADX. For I = 0 to N-1, replace DX(IX+IINCX) with DA * DX(IX+IINCX), where IX = 1 if INCX .GE. 0, else IX = 1+(1-N)INCX.
OPTIONS
N
number of elements in input vector(s)
DA
double precision scale factor
DX
double precision vector with N elements
INCX
storage spacing between elements of DX
RETURNS
DX
double precision result (unchanged if N.LE.0)
REFERENCES
B L A S Subprogram
C. L. Lawson, R. J. Hanson, D. R. Kincaid and F. T. Krogh, Basic linear algebra subprograms for Fortran usage, Algorithm No. 539, Transactions on Mathematical Software 5, 3 (September 1979), pp. 308-323.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
real(kind=dp), intent(in) :: Da
real(kind=dp), intent(inout) :: Dx(*)
integer, intent(in) :: Incx
Called by
Call graph
dainvg calls dscal, dgefa
dgefa calls dscal
dprepj calls dscal, dgefa
dprepji calls dscal, dgefa
dprja calls dscal, dgefa
dstodpk calls dscal
dstoka calls dscal
daigbt calls dgefa
dlsodi calls dainvg
dlsodkr calls dstoka
dlsodpk calls dstodpk
dpjibt calls dgefa
dlsoibt calls daigbt