dvnorm – odepack
dvnorm Function
13 statements
Source File
public pure function dvnorm(n, v, w)
NAME
dvnorm(3f) - [M_odepack] Weighted root-mean-square vector norm.
DESCRIPTION
This function routine computes the weighted root-mean-square norm of the vector of length N contained in the array V, with weights contained in the array W of length N:
    DVNORM = SQRT( (1/N) * SUM( V(i)*W(i) )**2 )
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=dp), intent(in) :: v(n)
real(kind=dp), intent(in) :: w(n)
Return Value real(kind=dp)
Called by
Call graph
dlhin calls dvnorm
dlsode calls dvnorm
dlsodes calls dvnorm
dlsodi calls dvnorm
dlsodis calls dvnorm
dlsodkr calls dvnorm, dlhin, dstoka
dlsodpk calls dvnorm, dstodpk
dlsoibt calls dvnorm
dprepj calls dvnorm
dprjs calls dvnorm
dstode calls dvnorm
dstodi calls dvnorm
dstodpk calls dvnorm
dstoka calls dvnorm